#define REASON_AUTHORIZED 0
#define REASON_HEALING 1
#define REASON_HEALING_GLOBAL 2
#define REASON_FATIGUE_TOGGLED 3
#define REASON_RESPAWN_TIMER_CHANGED 4

#define REASON_ARSENAL_OPENED 5
#define REASON_LOADOUT_SAVED 6
#define REASON_LOADOUT_APPLIED 7
#define REASON_LOADOUT_COPIED 8

#define REASON_RALLYPOINT_DEPLOYED 9
#define REASON_RALLYPOINT_SET 10
#define REASON_RALLYPOINT_REMOVED 11

#define REASON_GARAGE_OPENED 12
#define REASON_VEHICLE_REPAIR 13
#define REASON_VEHICLE_REFUEL 14
#define REASON_VEHICLE_REARM 15
#define REASON_VEHICLE_SET_IN_AIR 16
#define REASON_VEHICLE_LANDED 17
#define REASON_VEHICLE_HOVER_TOGGLED 18
#define REASON_VEHICLE_LEAVED 19
#define REASON_VEHICLE_DRIVER_ADDED 20
#define REASON_VEHICLE_DRIVER_REMOVED 21

#define REASON_PINNED_VEHICLE_PINNED 22
#define REASON_PINNED_VEHICLE_USED 23
#define REASON_PINNED_VEHICLE_DISABLED 24
#define REASON_PINNED_VEHICLE_ENABLED 25

#define REASON_WALLHACK_TOGGLED 26
#define REASON_WALLHACK_RANGE_CHANGED 27

#define REASON_CAMERA_OPENED 28
#define REASON_CONSOLE_OPENED 29

#define REASON_RATING_FIXED 30
#define REASON_RATING_FIXED_GLOBAL 31
#define REASON_GROUP_JOINED 32
#define REASON_GROUP_LEADERSHIP_TAKEN 33
#define REASON_GROUP_LEAVED 34
#define REASON_GROUP_UNIT_JOINED 35
#define REASON_GROUP_UNIT_ADDED 36
#define REASON_GROUP_UNIT_HEALED 37
#define REASON_GROUP_UNIT_RALLIED 38
#define REASON_GROUP_UNIT_LOADOUT_APPLIED 39
#define REASON_GROUP_UNIT_REARMED 40
#define REASON_GROUP_UNIT_REMOVED 41
#define REASON_GROUP_UNIT_ARSENAL_APPLIED 42
